#!/bin/bash

find beer -name "*.xml" | tr [A-Z] [a-z] | sed -e 's/^beer\///' > lowercase_beerdocs_list

while read beer_id ; do
	# echo $beer_id

	# Need to find out if this beer file already exists and do it with a case-insensitive search because Mac OS X's file system is case-insensitive
	
	brewery_id=${beer_id%%/*}
	# echo $(echo $beer_id|tr [A-Z] [a-z])=$(echo $brewery_id|tr [A-Z] [a-z])
	
	if grep $(echo $beer_id|tr [A-Z] [a-z]) lowercase_beerdocs_list; then
		echo $beer_id already exists;
	fi

	# if [ ! -d "beer/$brewery_id" ]; then
	# 	mkdir "beer/$brewery_id";
	# fi
	
	# beer_doc=$(xml sel -t -m "/beers/beer[@id=&quot;$beer_id&quot;]" -c . $1)
	# echo $beer_doc | xml fo > foo.xml
	
done < <(xml sel -t -m '/beers/beer' -v '@id' -n $1)

